"""
Evidence Manager
================
Manages the evidence vault: creates case/evidence directory structures,
writes metadata, maintains the chain of custody, enforces integrity,
supports tagging, and provides tamper-evident audit trails.

Usage:
    from core.chain_of_custody.evidence_manager import EvidenceManager

    mgr = EvidenceManager()
    ev_dir = mgr.create_evidence_entry(meta)
    mgr.write_metadata(meta)
    mgr.tag_evidence("CASE-001", "EV-ABC", ["ransomware", "windows"])
    mgr.record_custody_event(meta.evidence_id, meta.case_id, "transferred", "Analyst B")
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from loguru import logger

from core.acquisition.metadata_collector import AcquisitionMetadata
from core.config import settings


class EvidenceManager:
    """
    Manages the on-disk evidence vault.

    Directory layout:
        evidence/
        └── cases/
            └── <case_id>/
                └── <evidence_id>/
                    ├── metadata.json
                    ├── metadata.signed.json   (HMAC-signed copy)
                    ├── acquisition.log
                    ├── chain_of_custody.json
                    ├── tags.json
                    └── <image files>
    """

    def __init__(self, base_path: Path | None = None) -> None:
        self.base_path = Path(base_path or settings.evidence.base_path)
        self.cases_dir = self.base_path / "cases"
        self.cases_dir.mkdir(parents=True, exist_ok=True)
        logger.debug("EvidenceManager initialized | base={}", self.base_path)

    # ── Directory management ──────────────────────────────────────────────────

    def case_dir(self, case_id: str) -> Path:
        return self.cases_dir / case_id

    def evidence_dir(self, case_id: str, evidence_id: str) -> Path:
        return self.case_dir(case_id) / evidence_id

    def create_evidence_entry(self, meta: AcquisitionMetadata) -> Path:
        """Create the directory structure for a new evidence item."""
        ev_dir = self.evidence_dir(meta.case_id, meta.evidence_id)
        ev_dir.mkdir(parents=True, exist_ok=True)

        # Chain of custody
        coc_path = ev_dir / "chain_of_custody.json"
        if not coc_path.exists():
            self._write_json(
                coc_path,
                {
                    "evidence_id": meta.evidence_id,
                    "case_id": meta.case_id,
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "events": [],
                },
            )

        # Acquisition log
        log_path = ev_dir / "acquisition.log"
        if not log_path.exists():
            log_path.write_text(
                f"# Acquisition Log — {meta.evidence_id}\n"
                f"# Case: {meta.case_id}\n"
                f"# Examiner: {meta.examiner}\n"
                f"# Started: {meta.acquisition_start}\n"
                f"# Auto-generated by ForgeLens — do not edit manually\n\n",
                encoding="utf-8",
            )

        # Tags file
        tags_path = ev_dir / "tags.json"
        if not tags_path.exists():
            self._write_json(tags_path, {"evidence_id": meta.evidence_id, "tags": []})

        logger.info(
            "Evidence entry created | evidence_id={} | path={}",
            meta.evidence_id,
            ev_dir,
        )

        self.record_custody_event(
            meta.evidence_id,
            meta.case_id,
            event_type="created",
            actor=meta.examiner,
            notes=f"Acquisition started via {meta.acquisition_method}",
        )

        # Auto-index
        self._auto_index(meta.case_id, meta.evidence_id)

        return ev_dir

    # ── Metadata ──────────────────────────────────────────────────────────────

    def write_metadata(self, meta: AcquisitionMetadata) -> Path:
        """Write metadata.json to the evidence directory."""
        ev_dir = self.evidence_dir(meta.case_id, meta.evidence_id)
        ev_dir.mkdir(parents=True, exist_ok=True)
        meta_path = ev_dir / "metadata.json"
        self._write_json(meta_path, meta.to_dict())
        logger.info("Metadata written: {}", meta_path)

        # Re-index after metadata update
        self._auto_index(meta.case_id, meta.evidence_id, metadata=meta.to_dict())
        return meta_path

    def read_metadata(self, case_id: str, evidence_id: str) -> dict:
        """Read metadata.json for an evidence item."""
        meta_path = self.evidence_dir(case_id, evidence_id) / "metadata.json"
        if not meta_path.exists():
            raise FileNotFoundError(f"Metadata not found: {meta_path}")
        return json.loads(meta_path.read_text(encoding="utf-8"))

    # ── Tagging ───────────────────────────────────────────────────────────────

    def tag_evidence(
        self,
        case_id: str,
        evidence_id: str,
        tags: list[str],
        actor: str = "system",
    ) -> None:
        """
        Set tags on an evidence item.
        Tags are stored in tags.json and also updated in the index.
        """
        ev_dir = self.evidence_dir(case_id, evidence_id)
        tags_path = ev_dir / "tags.json"

        existing: list[str] = []
        if tags_path.exists():
            data = json.loads(tags_path.read_text(encoding="utf-8"))
            existing = data.get("tags", [])

        # Merge and deduplicate
        merged = sorted(set(existing + [t.lower().strip() for t in tags]))
        self._write_json(
            tags_path,
            {
                "evidence_id": evidence_id,
                "tags": merged,
                "updated_at": datetime.now(timezone.utc).isoformat(),
            },
        )

        # Update index
        try:
            from core.chain_of_custody.evidence_index import EvidenceIndex

            idx = EvidenceIndex(base_path=self.base_path)
            idx.update_tags(evidence_id, merged)
        except Exception as exc:
            logger.debug("Index tag update error: {}", exc)

        self.record_custody_event(
            evidence_id,
            case_id,
            event_type="tagged",
            actor=actor,
            notes=f"Tags set: {merged}",
        )
        logger.info("Evidence tagged | evidence_id={} | tags={}", evidence_id, merged)

    def get_tags(self, case_id: str, evidence_id: str) -> list[str]:
        """Return tags for an evidence item."""
        tags_path = self.evidence_dir(case_id, evidence_id) / "tags.json"
        if not tags_path.exists():
            return []
        return json.loads(tags_path.read_text(encoding="utf-8")).get("tags", [])

    # ── Chain of custody ──────────────────────────────────────────────────────

    def record_custody_event(
        self,
        evidence_id: str,
        case_id: str,
        event_type: str,
        actor: str,
        notes: str = "",
    ) -> None:
        """
        Append an immutable event to the chain of custody log.
        Events are append-only — never modified after writing.
        """
        coc_path = self.evidence_dir(case_id, evidence_id) / "chain_of_custody.json"

        if not coc_path.exists():
            self._write_json(
                coc_path,
                {
                    "evidence_id": evidence_id,
                    "case_id": case_id,
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "events": [],
                },
            )

        coc = json.loads(coc_path.read_text(encoding="utf-8"))
        event = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "event_type": event_type,
            "actor": actor,
            "notes": notes,
            "seq": len(coc["events"]) + 1,
        }
        coc["events"].append(event)
        self._write_json(coc_path, coc)

        logger.info(
            "CoC event | evidence_id={} | type={} | actor={} | seq={}",
            evidence_id,
            event_type,
            actor,
            event["seq"],
        )

    def get_custody_chain(self, case_id: str, evidence_id: str) -> list[dict]:
        """Return the full chain of custody event list."""
        coc_path = self.evidence_dir(case_id, evidence_id) / "chain_of_custody.json"
        if not coc_path.exists():
            return []
        return json.loads(coc_path.read_text(encoding="utf-8")).get("events", [])

    def get_audit_trail(self, case_id: str) -> list[dict]:
        """
        Return a merged, time-sorted audit trail for an entire case —
        all custody events from all evidence items.
        """
        events: list[dict] = []
        case_dir = self.case_dir(case_id)
        if not case_dir.exists():
            return events
        for ev_dir in case_dir.iterdir():
            if not ev_dir.is_dir():
                continue
            coc_path = ev_dir / "chain_of_custody.json"
            if coc_path.exists():
                coc = json.loads(coc_path.read_text(encoding="utf-8"))
                for ev in coc.get("events", []):
                    ev["evidence_id"] = ev_dir.name
                    events.append(ev)
        return sorted(events, key=lambda e: e.get("timestamp", ""))

    # ── Integrity ─────────────────────────────────────────────────────────────

    def write_hash_file(
        self,
        case_id: str,
        evidence_id: str,
        filename: str,
        sha256: str,
        md5: str = "",
        sha1: str = "",
    ) -> Path:
        """Write a hash manifest sidecar file."""
        ev_dir = self.evidence_dir(case_id, evidence_id)
        hash_path = ev_dir / f"{filename}.hashes"
        lines = [
            "# ForgeLens Hash Manifest",
            f"# File: {filename}",
            f"# Generated: {datetime.now(timezone.utc).isoformat()}",
            "",
            "# --- Acquisition Image Hashes (hash of the captured image) ---",
            f"SHA256: {sha256}",
        ]
        if md5:
            lines.append(f"MD5:    {md5}")
        if sha1:
            lines.append(f"SHA1:   {sha1}")
        hash_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Hash manifest written: {}", hash_path)
        return hash_path

    def write_logical_manifest(
        self,
        case_id: str,
        evidence_id: str,
        file_hashes: dict[str, str],
    ) -> Path:
        """Write a hash manifest sidecar file for all files in a logical acquisition."""
        ev_dir = self.evidence_dir(case_id, evidence_id)
        manifest_path = ev_dir / "logical_manifest.hashes"
        lines = [
            "# ForgeLens Logical Hash Manifest",
            f"# Generated: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]
        for rel_path, sha256 in sorted(file_hashes.items()):
            lines.append(f"{rel_path}: {sha256}")
        manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Logical hash manifest written: {}", manifest_path)
        return manifest_path

    def verify_evidence_integrity(
        self,
        case_id: str,
        evidence_id: str,
        image_filename: str,
    ) -> bool:
        """Re-hash the image and compare against stored hashes."""
        from core.hashing.hasher import HashAlgorithm, Hasher

        ev_dir = self.evidence_dir(case_id, evidence_id)
        image_path = ev_dir / image_filename
        hash_path = ev_dir / f"{image_filename}.hashes"

        if not image_path.exists():
            logger.error("Image file not found: {}", image_path)
            return False
        if not hash_path.exists():
            logger.error("Hash manifest not found: {}", hash_path)
            return False

        stored: dict[str, str] = {}
        for line in hash_path.read_text(encoding="utf-8").splitlines():
            if ":" in line and not line.startswith("#"):
                algo, digest = line.split(":", 1)
                stored[algo.strip().lower()] = digest.strip()

        if "sha256" in stored:
            ok = Hasher.verify_file(image_path, HashAlgorithm.SHA256, stored["sha256"])
            if not ok:
                self.record_custody_event(
                    evidence_id,
                    case_id,
                    event_type="integrity_failed",
                    actor="system",
                    notes="SHA256 mismatch — possible tampering",
                )
                return False

        self.record_custody_event(
            evidence_id,
            case_id,
            event_type="verified",
            actor="system",
            notes="Integrity check passed",
        )
        logger.info("Integrity verified: {}", image_filename)
        return True

    def verify_logical_integrity(
        self,
        case_id: str,
        evidence_id: str,
    ) -> bool:
        """Re-hash all files in the logical evidence folder and compare against stored hashes."""
        from core.hashing.hasher import HashAlgorithm, Hasher

        ev_dir = self.evidence_dir(case_id, evidence_id)
        manifest_path = ev_dir / "logical_manifest.hashes"

        if not manifest_path.exists():
            logger.error("Logical manifest not found: {}", manifest_path)
            return False

        stored: dict[str, str] = {}
        for line in manifest_path.read_text(encoding="utf-8").splitlines():
            if ":" in line and not line.startswith("#"):
                rel_path, digest = line.split(":", 1)
                stored[rel_path.strip()] = digest.strip()

        success = True
        missing = []
        mismatched = []

        for rel_path, expected_hash in stored.items():
            file_path = ev_dir / rel_path
            if not file_path.exists():
                missing.append(rel_path)
                success = False
                continue

            ok = Hasher.verify_file(file_path, HashAlgorithm.SHA256, expected_hash)
            if not ok:
                mismatched.append(rel_path)
                success = False

        if not success:
            notes = []
            if missing:
                notes.append(f"Missing: {missing}")
            if mismatched:
                notes.append(f"Mismatched: {mismatched}")
            self.record_custody_event(
                evidence_id,
                case_id,
                event_type="integrity_failed",
                actor="system",
                notes="Logical verification failed: " + "; ".join(notes),
            )
            return False

        self.record_custody_event(
            evidence_id,
            case_id,
            event_type="verified",
            actor="system",
            notes="Logical integrity check passed",
        )
        logger.info("Logical integrity verified for: {}", evidence_id)
        return True

    def write_signed_metadata(
        self,
        meta: AcquisitionMetadata,
        key: bytes,
    ) -> Path:
        """Write HMAC-signed metadata for tamper detection."""
        from core.chain_of_custody.vault_crypto import VaultCrypto

        ev_dir = self.evidence_dir(meta.case_id, meta.evidence_id)
        signed_path = ev_dir / "metadata.signed.json"
        VaultCrypto.write_signed_metadata(meta.to_dict(), signed_path, key)
        return signed_path

    def verify_signed_metadata(
        self,
        case_id: str,
        evidence_id: str,
        key: bytes,
    ) -> tuple[dict, bool]:
        """Read and verify HMAC-signed metadata."""
        from core.chain_of_custody.vault_crypto import VaultCrypto

        signed_path = self.evidence_dir(case_id, evidence_id) / "metadata.signed.json"
        return VaultCrypto.read_and_verify_metadata(signed_path, key)

    # ── Case listing ──────────────────────────────────────────────────────────

    def list_cases(self) -> list[str]:
        """Return all case IDs in the vault."""
        if not self.cases_dir.exists():
            return []
        return [d.name for d in self.cases_dir.iterdir() if d.is_dir()]

    def list_evidence(self, case_id: str) -> list[str]:
        """Return all evidence IDs for a case."""
        case_dir = self.case_dir(case_id)
        if not case_dir.exists():
            return []
        return [d.name for d in case_dir.iterdir() if d.is_dir()]

    # ── Internal ──────────────────────────────────────────────────────────────

    def _auto_index(
        self,
        case_id: str,
        evidence_id: str,
        metadata: dict | None = None,
    ) -> None:
        """Auto-index evidence into the search index."""
        try:
            from core.chain_of_custody.evidence_index import EvidenceIndex

            idx = EvidenceIndex(base_path=self.base_path)
            tags = self.get_tags(case_id, evidence_id)
            idx.index_evidence(case_id, evidence_id, tags=tags, metadata=metadata)
        except Exception as exc:
            logger.debug("Auto-index error: {}", exc)

    @staticmethod
    def _write_json(path: Path, data: dict) -> None:
        path.write_text(
            json.dumps(data, indent=2, default=str),
            encoding="utf-8",
        )
